### ISSUE TITLE
Why not just create a hardware interface for ros2_control?

### ISSUE THREAD

**Issue by resizoltan** [kroshu/ros2_kuka_sunrise#10]
The de-facto control framework for ROS is ros_control, which is currently being ported to ROS2. A detailed reasoning should be provided why nodes are created for the driver instead of just implementing a hardware interface so that the robot can be used with ros2_control.

**Comment by kovacsge11** [comment]
The main reason was that the porting of ros_control was still undergoing, right? Or am I missing something? Are there any further reasons? @resizoltan

**Comment by kovacsge11** [comment]
As @Svastits correctly stated, he added some extra features already which are useful for his project. We don't see yet how exactly these features could be mapped to ros2_control, we're not entirely sure that it's possible. We'll take a look at it.

**Comment by Groebehavn** [comment]
Could you name the features you added, which might be problematic? @Svastits @kovacsge11 ?

**Comment by resizoltan** [comment]
These types of features are very useful and a core element of any control stack imo. I don't know how exactly they are implemented in ros2_control. But I don't think this issue has any influence on our work right now, since this does not invalidate what we want to do, only shows a desired control stack functionality that has to be implemented if this approach is pursued.
