### ISSUE TITLE
Evaluate GitHub actions for pipeline builds

### ISSUE THREAD

**Issue by resizoltan** [kroshu/ros2_kuka_sunrise#14]
Industrial CI also runs on GitHub actions. Main reason to consider switching: Travis-CI does not support skipping builds if only certain files or directories have changed (travis-ci/travis-ci#6301). This would be quite relevant for the documentation folder - it makes no sense to trigger a build when updating it.

**Comment by kovacsge11** [comment]
I fully support this. I've read the same about skipping builds.

**Comment by Groebehavn** [comment]
PR into master, great! :) Can we consider this as closed? All builds are migrated? Or are there any left out?

**Comment by kovacsge11** [comment]
It's only done for this repo, and it's still sitting on prepare-for-open-collab branch. When we have an initial somewhat-ready state, we can merge to master imo.
